name: Topo Telemetry
on:
  project_v2_item:
    types: [created, edited, moved, deleted]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Signal to Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: "The Topo"
          details: "Roadmap Update: A task has been updated on SurvivalStack."
          webhookUrl: ${{ secrets.DISCORD_PROJECT_WEBHOOK }}